### ISSUE TITLE
Addition to file reading section

### ISSUE THREAD

**Issue by pcmathias** [pcmathias/MSACL-intermediate-R-course#19]
Add catalog of common file formats to read/parse

**Comment by pcmathias** [comment]
Also add example of map functions to iterate and read in multiple files in one folder

**Comment by rkjulian** [comment]
Lesson 10 uses map_dfr() so it would be good to explain those functions before getting to the final project.

**Comment by pcmathias** [comment]
I have it covered in lesson 3.

-Patrick

________________________________

**Comment by rkjulian** [comment]
I merged my branch into master with no conflicts, so your merge should now include all my new stuff.

Randy
