### ISSUE TITLE
Remove PDF as default knitr output

### ISSUE THREAD

**Issue by rkjulian** [pcmathias/MSACL-intermediate-R-course#33]
Almost nobody on Windows will have TEX installed - the default should be HTML (for class purposes)

**Comment by pcmathias** [comment]
Added tinytex package to pre-course work. Will try to test out on a fresh Windows machine to confirm. Will focus on html in class though.

**Comment by rkjulian** [comment]
I recommend that you make the tinytex part of course (one of the lessons) I can test it on my windows machine (which as no Tex). People love making PDF files and I hate working with HTML and Word output is a bit ugly.

Thanks for the pointers to the answers and I will gut the lattice bits out of the visualization and we can maybe make that the place to discuss tinytex

**Comment by rkjulian** [comment]
Sounds good. I’ll leave the base plot and the ggplot2 content in lesson 6, and we can ask people if they want to dig into that material or not.

I almost have all of the raw data converted to csv, then I will fix lesson 10.

Randy
